package restaurantepresentacion;

import Interfaces.IClienteFrecuenteBO;
import Interfaces.IComandaBO;
import Interfaces.IMesaBO;
import Interfaces.IProductoBO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import restaurantedominio.ClienteFrecuente;
import restaurantedtos.ClienteFrecuenteDTO;
import restaurantedtos.ComandaDTO;
import restaurantedtos.MesaDTO;
import restaurantedtos.ProductoDTO;

/**
 *
 * @author Dell
 */
public class AbrirComandaFORM extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AbrirComandaFORM.class.getName());

    // 1. Declaramos los objetos BO que usará esta pantalla
    private IMesaBO mesaBO;
    private IProductoBO productoBO;
    private IClienteFrecuenteBO clienteBO;
    private IComandaBO comandaBO;

    private restaurantedtos.ClienteFrecuenteDTO clienteSeleccionado;
    private javax.swing.table.DefaultTableModel modeloMenu;
    private javax.swing.table.DefaultTableModel modeloOrden;

    public AbrirComandaFORM() {
        initComponents();

        this.mesaBO = new restaurantenegocio.MesaBO();
        this.productoBO = new restaurantenegocio.ProductoBO();
        this.clienteBO = new restaurantenegocio.ClienteFrecuenteBO();
        this.comandaBO = new restaurantenegocio.ComandaBO();

        // Inicializamos las tablas y cargamos los datos
        configurarTablas();
        llenarComboBoxMesas();
        llenarTablaMenu("Platillo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMesa = new javax.swing.JLabel();
        ComboBoxMesa = new javax.swing.JComboBox<>();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMenu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaOrden = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnAbrirComanda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPlatillo = new javax.swing.JButton();
        btnBebida = new javax.swing.JButton();
        btnPostre = new javax.swing.JButton();
        lblClienteSeleccionado = new javax.swing.JLabel();
        btnQuitar = new javax.swing.JButton();
        lblMesa1 = new javax.swing.JLabel();
        txtComentarios = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMesa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMesa.setText("Mesa");

        ComboBoxMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCliente.setText("Celular:");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar Cliente");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMenu);

        tablaOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaOrden);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText("Total: $0.00");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAbrirComanda.setText("Abrir Comanda");
        btnAbrirComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirComandaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Realizar la comanda");

        btnPlatillo.setText("Platillo");
        btnPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatilloActionPerformed(evt);
            }
        });

        btnBebida.setText("Bebida");
        btnBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidaActionPerformed(evt);
            }
        });

        btnPostre.setText("Postre");
        btnPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostreActionPerformed(evt);
            }
        });

        lblClienteSeleccionado.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lblClienteSeleccionado.setText("Cliente frecuente");

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        lblMesa1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMesa1.setText("Comentarios:");

        txtComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComentariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnPlatillo)
                        .addGap(18, 18, 18)
                        .addComponent(btnBebida)
                        .addGap(18, 18, 18)
                        .addComponent(btnPostre)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnQuitar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotal)
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnAbrirComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMesa)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(lblCliente)
                                .addGap(18, 18, 18)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(34, 34, 34)
                                .addComponent(lblClienteSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMesa1)
                .addGap(395, 395, 395))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMesa)
                    .addComponent(ComboBoxMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(lblClienteSeleccionado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlatillo)
                    .addComponent(btnBebida)
                    .addComponent(btnPostre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnQuitar)
                    .addComponent(lblTotal))
                .addGap(30, 30, 30)
                .addComponent(lblMesa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAbrirComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtComentarios))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed

    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidaActionPerformed
        llenarTablaMenu("Bebida");
    }//GEN-LAST:event_btnBebidaActionPerformed

    private void btnPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatilloActionPerformed
        llenarTablaMenu("Platillo");
    }//GEN-LAST:event_btnPlatilloActionPerformed

    private void btnPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostreActionPerformed
        llenarTablaMenu("Postre");
    }//GEN-LAST:event_btnPostreActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String telefono = txtCliente.getText().trim();

        if (telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un teléfono para buscar.");
            return;
        }

        try {
            // Buscamos al cliente
            ClienteFrecuente clienteBD = clienteBO.buscarPorTelefono(telefono);

            if (clienteBD != null) {
                // Si lo encuentrs
                lblClienteSeleccionado.setText("Cliente: " + clienteBD.getNombre() + " " + clienteBD.getApellidoPaterno());

                // Lo guardamos en DTO
                clienteSeleccionado = new ClienteFrecuenteDTO();
                clienteSeleccionado.setId(clienteBD.getId());
            } else {
                // Si no lo encuentra
                lblClienteSeleccionado.setText("No encontrado (Público General)");
                clienteSeleccionado = null; // null le dirá al BO que use el Cliente General
            }
        } catch (restaurantenegocio.NegocioException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());
            lblClienteSeleccionado.setText("Cliente frecuente");
            clienteSeleccionado = null;
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int filaSeleccionada = tablaMenu.getSelectedRow();

        // Validamos que si haya una tabla seleccionada
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto del menú para agregar.");
            return;
        }

        // Extraemos los datos de la fila seleccionada
        Long id = (Long) modeloMenu.getValueAt(filaSeleccionada, 0);
        String nombre = (String) modeloMenu.getValueAt(filaSeleccionada, 1);
        String precioStr = (String) modeloMenu.getValueAt(filaSeleccionada, 3);

        // Pasamos los datos a la tabla de la Orden
        modeloOrden.addRow(new Object[]{id, nombre, precioStr});

        // Actualizamos el total
        actualizarTotal();

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int filaSeleccionada = tablaOrden.getSelectedRow();

        // 1. Validamos que el mesero haya seleccionado algo en la tabla de la DERECHA
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto de la orden para quitar.");
            return;
        }

        // 2. Lo borramos y recalculamos el total
        modeloOrden.removeRow(filaSeleccionada);
        actualizarTotal();

    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnAbrirComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirComandaActionPerformed
        // Validamos que se haya seleccionado una mesa
        if (ComboBoxMesa.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una mesa disponible.");
            return;
        }

        // Validamos que haya productos en la orden
        if (modeloOrden.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "La comanda debe tener al menos un producto.");
            return;
        }

        try {
            // Sacamos el ID de la mesa seleccionada
            String mesaSeleccionada = (String) ComboBoxMesa.getSelectedItem();
            Long idMesa = Long.parseLong(mesaSeleccionada.split(" - ")[0]);

            MesaDTO mesaDTO = new MesaDTO();
            mesaDTO.setId(idMesa);

            // Recopilar todos los productos de la tabla orden
            List<ProductoDTO> productosComanda = new ArrayList<>();
            double totalCalculado = 0;

            for (int i = 0; i < modeloOrden.getRowCount(); i++) {
                Long idProducto = (Long) modeloOrden.getValueAt(i, 0);

                ProductoDTO prod = new ProductoDTO();
                prod.setId(idProducto);
                productosComanda.add(prod);

                // Calculamos el total
                String precioStr = (String) modeloOrden.getValueAt(i, 2);
                precioStr = precioStr.replace("$", "");
                totalCalculado += Double.parseDouble(precioStr);
            }

            // Armamos la ComandaDTO 
            ComandaDTO nuevaComanda = new ComandaDTO();
            nuevaComanda.setMesa(mesaDTO); // Le seteamos la mesa
            nuevaComanda.setCliente(clienteSeleccionado); // Le seteamos el cliente
            nuevaComanda.setProductos(productosComanda); // le seteamos la lista de productos de la orden
            nuevaComanda.setTotalVenta((long) totalCalculado); // Le seteamos el total
            String comentarios = txtComentarios.getText().trim();
            nuevaComanda.setComentarios(comentarios); // Le seteamos los comentarios

            // Usamos el supermetodo
            ComandaDTO comandaAbierta = comandaBO.abrirComanda(nuevaComanda);

            // JOptionPane de confirmacion
            JOptionPane.showMessageDialog(this, "¡Comanda abierta con éxito!\nFolio generado: " + comandaAbierta.getFolio());

            // Cerramos esta pantalla y regresamos
            this.dispose();
            new GestionClientesFORM().setVisible(true);

        } catch (restaurantenegocio.NegocioException ex) {
            // Si el BO rechaza la comanda
            JOptionPane.showMessageDialog(this, "No se pudo abrir la comanda:\n" + ex.getMessage(), "Alerta", JOptionPane.WARNING_MESSAGE);
        }
     }//GEN-LAST:event_btnAbrirComandaActionPerformed

    private void txtComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComentariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComentariosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        new GestionClientesFORM().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AbrirComandaFORM().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxMesa;
    private javax.swing.JButton btnAbrirComanda;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBebida;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPlatillo;
    private javax.swing.JButton btnPostre;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblClienteSeleccionado;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblMesa1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablaMenu;
    private javax.swing.JTable tablaOrden;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtComentarios;
    // End of variables declaration//GEN-END:variables

    private void configurarTablas() {
        // Configuramos tablas
        modeloMenu = new javax.swing.table.DefaultTableModel(new Object[]{"ID", "Nombre", "Tipo", "Precio"}, 0);
        tablaMenu.setModel(modeloMenu);

        modeloOrden = new javax.swing.table.DefaultTableModel(new Object[]{"ID", "Nombre", "Precio"}, 0);
        tablaOrden.setModel(modeloOrden);
    }

    private void llenarComboBoxMesas() {
        ComboBoxMesa.removeAllItems();
        ComboBoxMesa.addItem("Seleccione una mesa...");

        try {
            // Traemos todas las mesas
            java.util.List<restaurantedominio.Mesa> mesas = mesaBO.listarMesas();

            for (restaurantedominio.Mesa mesa : mesas) {
                // Solo agregamos las DISPONIBLES
                if (mesa.getDisponible() == EnumeradoresDominio.Disponibilidad.DISPONIBLE) {
                    // Guardamos el ID escondido en el texto para poder extraerlo después
                    ComboBoxMesa.addItem(mesa.getId() + " - Mesa " + mesa.getNumMesa());
                }
            }
        } catch (restaurantenegocio.NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las mesas: " + e.getMessage());
        }
    }

    private void llenarTablaMenu(String tipoFiltro) {
        modeloMenu.setRowCount(0);

        try {
            // Traemos los productos de la BD
            List<restaurantedominio.Producto> productos = productoBO.llenarTabla();

            for (restaurantedominio.Producto p : productos) {
                // Filtramos por tipo (Platillo, Bebida, Postre) y validamos que esté ACTIVO
                if (p.isActivo() && p.getTipo().equalsIgnoreCase(tipoFiltro)) {
                    modeloMenu.addRow(new Object[]{
                        p.getId(),
                        p.getNombre(),
                        p.getTipo(),
                        "$" + p.getPrecio()
                    });
                }
            }
        } catch (restaurantenegocio.NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el menú: " + e.getMessage());
        }
    }

    private void actualizarTotal() {
        double total = 0.0;

        // recorremos todas las filas
        for (int i = 0; i < modeloOrden.getRowCount(); i++) {
            String precio = (String) modeloOrden.getValueAt(i, 2);

            // Le quitamos el "$" 
            precio = precio.replace("$", "");
            total += Double.parseDouble(precio);
        }

        // Ponemos el total en la etiqueta
        lblTotal.setText(String.format("Total: $%.2f", total));
    }
}
