
package PanelesDinamicos;

import java.awt.Image;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import restaurantedominio.Ingrediente;
import EnumeradoresDominio.TipoUnidad;
import restaurantedtos.IngredienteActualizadoDTO;
import restaurantenegocio.IngredienteBO;
import restaurantenegocio.NegocioException;
import ImagenTabla.ImageTable;

/**
 *
 * @author Alex García Trejo
 */
public class BuscarIngredienteProductoInventarioPanel extends javax.swing.JPanel {

    private IngredienteBO ingredienteBO;
    private JSpinner spinner;
    private SpinnerNumberModel spinnerNumber;
    private static final Logger LOGGER = Logger.getLogger(BuscarIngredienteProductoInventarioPanel.class.getName());
    
    public BuscarIngredienteProductoInventarioPanel() {
        initComponents();
        ingredienteBO = new IngredienteBO(); 
        tbIngredientes.setRowHeight(60);
        tbIngredientes.getColumnModel().getColumn(4).setCellRenderer(new ImageTable());
        spinnerNumber = new SpinnerNumberModel(1, 1, 100, 1);
        spinner = new JSpinner();
        spinner.setModel(spinnerNumber);
        ((JSpinner.DefaultEditor) spinner.getEditor()).getTextField().setEditable(false);
        llenarTabla();
        cargarUnidadesCombo();
    }
    
    private void llenarTabla(List<Ingrediente> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tbIngredientes.getModel();
        modelo.setRowCount(0); 
        for (Ingrediente i: lista) {
            JLabel lbImage = new JLabel();
            if (i.getImagen() != null) {
                ImageIcon icon = new ImageIcon(i.getImagen());
                Image image = icon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                lbImage.setIcon(new ImageIcon(image));
            }
            Object[] fila = {
                i.getId(),
                i.getNombre(),
                i.getCantidad(),       
                i.getUnidad(),
                lbImage
            };
            modelo.addRow(fila);
        }
    }
    
    private void llenarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tbIngredientes.getModel();
        modelo.setRowCount(0); 
        List<Ingrediente> ingredientes;
        try {
            ingredientes = ingredienteBO.llenarTabla();
            for (Ingrediente i: ingredientes) {
                JLabel lbImage = new JLabel();
                if (i.getImagen() != null) {
                    ImageIcon icon = new ImageIcon(i.getImagen());
                    Image image = icon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                    lbImage.setIcon(new ImageIcon(image));
                }                
                Object[] fila = {
                    i.getId(),
                    i.getNombre(),
                    i.getCantidad(),
                    i.getUnidad(),
                    lbImage
                };
                modelo.addRow(fila);
            }
        } catch (NegocioException ex) {
            LOGGER.severe(ex.getMessage());
        }       
    }
    
    private void actualizarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tbIngredientes.getModel();
        modelo.setRowCount(0); 
        List<Ingrediente> ingredientes;
        try {
            ingredientes = ingredienteBO.llenarTabla();
            for (Ingrediente i: ingredientes) {
                JLabel lbImage = new JLabel();
                if (i.getImagen() != null) {
                    ImageIcon icon = new ImageIcon(i.getImagen());
                    Image image = icon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                    lbImage.setIcon(new ImageIcon(image));
                }                
                Object[] fila = {
                    i.getId(),
                    i.getNombre(),
                    i.getCantidad(),
                    i.getUnidad(),
                    lbImage
                };
                modelo.addRow(fila);
            }
        } catch (NegocioException ex) {
            LOGGER.severe(ex.getMessage());
        }       
    }
    
    private void cargarUnidadesCombo() {
        DefaultComboBoxModel<TipoUnidad> model = new DefaultComboBoxModel<>();
        model.addElement(null);
        for (TipoUnidad i: TipoUnidad.values()) {
            model.addElement(i);
        }
        comboUnidades.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboUnidades = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIngredientes = new javax.swing.JTable();
        btnInventario = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setBackground(new java.awt.Color(0, 102, 255));
        setPreferredSize(new java.awt.Dimension(719, 540));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Inventario ingredientes");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Unidad:");

        comboUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUnidadesActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tbIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Unidad", "Imagen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbIngredientes);

        btnInventario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnInventario.setText("Inventariar");
        btnInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboUnidades, 0, 240, Short.MAX_VALUE)
                            .addComponent(txtNombre))
                        .addGap(353, 353, 353))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(comboUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUnidadesActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombre = txtNombre.getText();
        TipoUnidad unidad = (TipoUnidad) comboUnidades.getSelectedItem();        

        try {
            List<Ingrediente> lista = ingredienteBO.buscarPorNombreUnidad(nombre, unidad);
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No existen ingredientes con parametros de busqueda.");
                return;
            }
            llenarTabla(lista);
        } catch (NegocioException e) {
            LOGGER.severe(e.getMessage());
            JOptionPane.showMessageDialog(
            this,
            "Erro al buscar ingrediente: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
            ); 
        }        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        int fila = tbIngredientes.getSelectedRow();
        
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un ingrediente para iniciar inventariado.");
            return;
        }
        
        int result = JOptionPane.showConfirmDialog(this, spinner, "Ingrese cantidad", JOptionPane.OK_CANCEL_OPTION);
        if (result != JOptionPane.OK_OPTION) {
            return;
        }   
        BigDecimal cantidad;
        try {
            Long id = (Long) tbIngredientes.getValueAt(fila, 0);
            int cantidadI = (int) spinner.getValue();           
            cantidad = new BigDecimal(cantidadI);
            
            IngredienteActualizadoDTO ingrediente = new IngredienteActualizadoDTO(id, cantidad);            
            ingredienteBO.inventariarIngrediente(ingrediente);
            
            JOptionPane.showMessageDialog(this, "Cantidad actualizada correctamente");
            actualizarTabla();
        } catch (NegocioException e) {
            LOGGER.severe(e.getMessage());
            JOptionPane.showMessageDialog(this, "Error al actualizar cantidad.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInventario;
    private javax.swing.JComboBox<TipoUnidad> comboUnidades;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbIngredientes;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
