
package PanelesDinamicos;

import Controlador.Control;
import Interfaces.IIngredienteBO;
import Interfaces.IProductoBO;
import Interfaces.IProductoIngredientesBO;
import java.util.List;
import restaurantedominio.Producto;
import restaurantedtos.IngredienteDTO;
import restaurantedtos.ProductoDTO;

/**
 *
 * @author Jaime
 */
public class CrearRecetaPanel extends javax.swing.JPanel {

    private Producto productoActual;     
    private Control control;
    
    private List<IngredienteDTO> listaIngredientesDisponibles;
    private List<ProductoDTO> listaProductosDisponibles;
    
    public CrearRecetaPanel(Control control) {
        this.control = control;
        initComponents();
        cargarIngredientesAlCombo(); 
        cargarProductosAlCombo();
    }
    
    public CrearRecetaPanel(restaurantedominio.Producto productoBase) {
        initComponents();
        this.productoActual = productoBase;
        
        cargarIngredientesAlCombo(); 
        cargarProductosAlCombo(); 
        llenarTablaReceta(); 
    }
    
    private void cargarIngredientesAlCombo() {
        try {
            cbIngredientes.removeAllItems(); 
            listaIngredientesDisponibles = control.consultarTodosLosIngredientes(); 
            for (restaurantedtos.IngredienteDTO ing : listaIngredientesDisponibles) {
                cbIngredientes.addItem(ing.getNombre()); 
            }
        } catch (Exception e) {
            System.out.println("Error en ingredientes: " + e.getMessage());
        }
    }
    
    private void cargarProductosAlCombo() {
        try {
            cbProductos.removeAllItems();
            listaProductosDisponibles = control.obtenerProductos(); 
            for (restaurantedtos.ProductoDTO prod : listaProductosDisponibles) {
                cbProductos.addItem(prod.getNombre());
            }
        } catch (Exception e) {
            System.out.println("Error en productos: " + e.getMessage());
        }
    }
    
    private void llenarTablaReceta() {
        if (productoActual == null || productoActual.getId() == null) return;
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tbReceta.getModel();
        modelo.setRowCount(0); 
        
        try {
            java.util.List<restaurantedominio.ProductoIngredientes> receta = control.obtenerIngredientesPorProducto(productoActual.getId());
            for (restaurantedominio.ProductoIngredientes pi : receta) {
                Object[] fila = { 
                    pi.getIngredientes().getNombre(), 
                    pi.getCantidad(), 
                    pi.getIngredientes().getUnidad() 
                };
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println("Error en tabla: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReceta = new javax.swing.JTable();
        btnAgregarIngrediente = new javax.swing.JButton();
        cbProductos = new javax.swing.JComboBox();
        cbIngredientes = new javax.swing.JComboBox();
        txtCantidadIngrediente = new javax.swing.JTextField();
        lblUnidad = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 255));

        tbReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingredientes", "Cantidad", "Unidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbReceta);
        if (tbReceta.getColumnModel().getColumnCount() > 0) {
            tbReceta.getColumnModel().getColumn(0).setResizable(false);
            tbReceta.getColumnModel().getColumn(1).setResizable(false);
            tbReceta.getColumnModel().getColumn(2).setResizable(false);
        }

        btnAgregarIngrediente.setText("Agregar Ingrediente");
        btnAgregarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarIngredienteActionPerformed(evt);
            }
        });

        cbProductos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductosActionPerformed(evt);
            }
        });

        cbIngredientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIngredientesActionPerformed(evt);
            }
        });

        txtCantidadIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadIngredienteActionPerformed(evt);
            }
        });

        lblUnidad.setText("text");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setText("Agregar a Receta");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel6.setText("Cantidad:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel7.setText("Producto:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel8.setText("Ingredientes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUnidad))
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCantidadIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUnidad))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIngredienteActionPerformed
        if (productoActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona o registra un producto primero.");
            return;
        }
        int indexCombo = cbIngredientes.getSelectedIndex();
        if (indexCombo == -1) return;
        
        String cantidadStr = txtCantidadIngrediente.getText().trim();
        if (cantidadStr.isEmpty()) return;
        
        restaurantedtos.IngredienteDTO ingDTO = listaIngredientesDisponibles.get(indexCombo);
        
        try {
            restaurantedominio.Ingrediente ingredienteEntidad = new restaurantedominio.Ingrediente();
            ingredienteEntidad.setId(ingDTO.getId()); 
            
            restaurantedominio.ProductoIngredientes nuevaRelacion = new restaurantedominio.ProductoIngredientes();
            nuevaRelacion.setProductos(productoActual);
            nuevaRelacion.setIngredientes(ingredienteEntidad);
            nuevaRelacion.setCantidad(new java.math.BigDecimal(cantidadStr)); 
            
            control.agregarProductoIngrediente(nuevaRelacion);
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Ingrediente agregado a la receta!");
            txtCantidadIngrediente.setText(""); 
            llenarTablaReceta(); 
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarIngredienteActionPerformed

    private void cbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductosActionPerformed
        int index = cbProductos.getSelectedIndex();
        if (index == -1 || listaProductosDisponibles == null) return;
        
        restaurantedtos.ProductoDTO prodDTO = listaProductosDisponibles.get(index);
        restaurantedominio.Producto prodEntidad = new restaurantedominio.Producto();
        prodEntidad.setId(prodDTO.getId());
        prodEntidad.setNombre(prodDTO.getNombre());
        
        this.productoActual = prodEntidad; 
        llenarTablaReceta(); 
    }//GEN-LAST:event_cbProductosActionPerformed

    private void cbIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIngredientesActionPerformed
        int index = cbIngredientes.getSelectedIndex();
        if (index == -1 || listaIngredientesDisponibles == null || listaIngredientesDisponibles.isEmpty()) return;
        
       
        restaurantedtos.IngredienteDTO ing = listaIngredientesDisponibles.get(index);
        
        
        if (ing.getUnidad() != null) {
            lblUnidad.setText(ing.getUnidad().toString());
        } else {
            lblUnidad.setText("Unidades");
        }
    }//GEN-LAST:event_cbIngredientesActionPerformed

    private void txtCantidadIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadIngredienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarIngrediente;
    private javax.swing.JComboBox cbIngredientes;
    private javax.swing.JComboBox cbProductos;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JTable tbReceta;
    private javax.swing.JTextField txtCantidadIngrediente;
    // End of variables declaration//GEN-END:variables
}