package restaurantepresentacionFORMS;

import Controlador.Control;
import restaurantepresentacionFORMS.ComandasActivasFORM;
import Interfaces.IClienteFrecuenteBO;
import Interfaces.IComandaBO;
import Interfaces.IMesaBO;

/**
 *
 * @author Dell
 */
public class CobrarComandaFORM extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CobrarComandaFORM.class.getName());
    private Long idComandaActual;
    private double totalVenta;
    private IComandaBO comandaBO;
    private IClienteFrecuenteBO clienteBO;
    private IMesaBO mesaBO;
    
    private Control control;

    public CobrarComandaFORM(Long idComanda, String totalTexto) {
        initComponents();

        this.idComandaActual = idComanda;
        this.comandaBO = new restaurantenegocio.ComandaBO();
        this.clienteBO = new restaurantenegocio.ClienteFrecuenteBO();
        this.mesaBO = new restaurantenegocio.MesaBO();
        String totalLimpio = totalTexto.replace("$", "").trim();
        this.totalVenta = Double.parseDouble(totalLimpio);

        // Mostramos el total en la pantalla
        lblTotalPagar.setText("Total a Pagar: $" + String.format("%.2f", totalVenta));

        // Le agregamos un evento al campo de texto para que calcule el cambio automáticamente mientras escribes
        txtEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calcularCambio();
            }
        });
    }

    public CobrarComandaFORM(Control control) {
        initComponents();
    }

    private void calcularCambio() {
        try {
            String efectivoStr = txtEfectivo.getText().trim();
            if (efectivoStr.isEmpty()) {
                lblCambio.setText("Cambio: $0.00");
                return;
            }

            double efectivo = Double.parseDouble(efectivoStr);
            double cambio = efectivo - totalVenta;

            if (cambio >= 0) {
                lblCambio.setText("Cambio: $" + String.format("%.2f", cambio));
                lblCambio.setForeground(new java.awt.Color(0, 153, 0)); // Color verde
            } else {
                lblCambio.setText("Faltan: $" + String.format("%.2f", Math.abs(cambio)));
                lblCambio.setForeground(java.awt.Color.RED); // Color rojo si falta dinero
            }
        } catch (NumberFormatException e) {
            lblCambio.setText("Ingrese un número válido");
        }
    }

    /**
     * Creates new form CobrarComandaFORM
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalPagar = new javax.swing.JLabel();
        lblefectivoRecibido = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JTextField();
        lblCambio = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTotalPagar.setText("Total a Pagar: $0.00");

        lblefectivoRecibido.setText("Efectivo Recibido:");

        txtEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEfectivoActionPerformed(evt);
            }
        });

        lblCambio.setText("Cambio: $0.00");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnPagar.setText("PAGAR Y CERRAR COMANDA");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(btnPagar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalPagar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblefectivoRecibido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCambio))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTotalPagar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblefectivoRecibido)
                    .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEfectivoActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {
            // 1. Validar el pago
            String efectivoStr = txtEfectivo.getText().trim();
            if (efectivoStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese la cantidad recibida.");
                return;
            }
            
            double efectivo = Double.parseDouble(efectivoStr);
            if (efectivo < totalVenta) {
                javax.swing.JOptionPane.showMessageDialog(this, "El efectivo no es suficiente para cubrir la cuenta.");
                return;
            }

            // 2. Buscamos la comanda original en la BD para saber qué mesa y cliente tiene
            restaurantedominio.Comanda comandaCerrar = comandaBO.consultarComanda(idComandaActual);

            // 3. ACTUALIZAR PUNTOS DEL CLIENTE (Si no es Público General)
            if (comandaCerrar.getCliente() != null) {
                clienteBO.actualizarVisita(comandaCerrar.getCliente().getId(), totalVenta);
            }

            // 4. LIBERAR LA MESA (Pasarla a DISPONIBLE)
            mesaBO.cambiarDisponibilidad(comandaCerrar.getMesa().getId(), EnumeradoresDominio.Disponibilidad.DISPONIBLE);

            // 5. CERRAR LA COMANDA (Aquí asumo que tienes un método entregarComanda o cerrarComanda en tu BO)
            // Si tu método se llama distinto, cámbialo aquí abajo:
            comandaBO.entregarComanda(idComandaActual); 

            // 6. Mensaje de éxito y fin del ciclo
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "¡Cobro realizado con éxito!\nCambio a entregar: $" + String.format("%.2f", (efectivo - totalVenta)));

            // Regresamos a la pantalla de Comandas Activas
            this.dispose();
            control.mostrarComandasActivasFORM();
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese una cantidad numérica válida.");
        } catch (restaurantenegocio.NegocioException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar el cobro: " + ex.getMessage());
        }
    
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        control.mostrarCobrarComandaFORM();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JLabel lblefectivoRecibido;
    private javax.swing.JTextField txtEfectivo;
    // End of variables declaration//GEN-END:variables
}