
package restaurantepresentacionFORMS;

import Controlador.Control;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ComandasActivasFORM extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ComandasActivasFORM.class.getName());

    private DefaultTableModel modeloComandas;
    private Control control;
    
    public ComandasActivasFORM(Control control) {
        this.control = control;
        initComponents();
        // Configuramos y llenamos la tabla
        configurarTabla();
        llenarTablaActivas();
    }

    private void configurarTabla() {
        // Colocamos los datos en la tabla
        modeloComandas = new DefaultTableModel(
                new Object[]{"ID", "Folio", "Mesa", "Cliente", "Total Actual"}, 0
        );
        tablaComandas.setModel(modeloComandas);

        // Opcional: Ocultar la columna ID para que el usuario no la vea, pero nosotros sí la usemos
        tablaComandas.getColumnModel().getColumn(0).setMinWidth(0);
        tablaComandas.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaComandas.getColumnModel().getColumn(0).setWidth(0);
    }

    private void llenarTablaActivas() {
        modeloComandas.setRowCount(0); // Limpiar tabla

        try {
            // Traemos las comandas de la BD
            java.util.List<restaurantedominio.Comanda> listaActivas = control.obtenerComandasActivas();

            for (restaurantedominio.Comanda c : listaActivas) {
                // Validamos si tiene cliente o es público general
                String nombreCliente = (c.getCliente() != null)
                        ? c.getCliente().getNombre() + " " + c.getCliente().getApellidoPaterno()
                        : "Público General";

                modeloComandas.addRow(new Object[]{
                    c.getId(), // El ID oculto
                    c.getFolio(),
                    "Mesa " + c.getMesa().getNumMesa(),
                    nombreCliente,
                    "$" + c.getTotalVenta()
                });
            }
        } catch (restaurantenegocio.NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar las comandas: " + ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComandasActivas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComandas = new javax.swing.JTable();
        btnEditarOrden = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblComandasActivas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblComandasActivas.setText("Comandas Activas");

        tablaComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaComandas);

        btnEditarOrden.setText("Editar Orden");
        btnEditarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarOrdenActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnCobrar.setText("Cobrar Comanda");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(lblComandasActivas)
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(btnEditarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblComandasActivas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarOrdenActionPerformed
        int fila = tablaComandas.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una comanda de la tabla para editarla.");
            return;
        }
        
        // Agarramos el ID oculto
        Long idComanda = (Long) modeloComandas.getValueAt(fila, 0);
        
        // Cerramos esta pantalla y abrimos la de edición
        this.dispose();
        control.mostrarEditarComandaFORM(idComanda);
    }//GEN-LAST:event_btnEditarOrdenActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        control.mostrarGestionClientesFORM();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        int fila = tablaComandas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una comanda de la tabla para cobrar.");
            return;
        }
        
        // Agarramos el ID y el Total de la fila seleccionada
        Long idComanda = (Long) modeloComandas.getValueAt(fila, 0);
        String totalTexto = (String) modeloComandas.getValueAt(fila, 4);
        
        
        // Abrimos la pantalla de cobro
        this.dispose();
        control.mostrarCobrarComandaFORM(idComanda, totalTexto);
    }//GEN-LAST:event_btnCobrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnEditarOrden;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComandasActivas;
    private javax.swing.JTable tablaComandas;
    // End of variables declaration//GEN-END:variables
}